version: "3.3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=torlg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your-pass
  torlg:
    build: .
    command: bash start.sh
    ports:
      - "80:80"
    depends_on: 
      - db

